import os
import pandas as pd
import tempfile
import json
from typing import Dict, Any, List, Optional
from e2b import Sandbox

class DataAnalyzer:
    """Data analysis tool using E2B sandbox for secure code execution with Pandas."""

    def __init__(self):
        self.sandbox: Optional[Sandbox] = None

    def initialize_sandbox(self) -> None:
        """Initialize the E2B sandbox if not already done."""
        if self.sandbox is None:
            try:
                self.sandbox = Sandbox()
                self.sandbox.run_code("pip install pandas")
                print("Data analyzer sandbox initialized successfully.")
            except Exception as e:
                print(f"Failed to initialize sandbox: {e}")
                print("Data analyzer will work in fallback mode without sandbox.")
                self.sandbox = None

    def _upload_file_to_sandbox(self, file_path: str) -> str:
        """Upload file to sandbox and return remote path."""
        remote_path = f"/tmp/{os.path.basename(file_path)}"
        with open(file_path, 'rb') as f:
            self.sandbox.files.write(remote_path, f.read())
        return remote_path

    def _parse_execution_result(self, result) -> Dict[str, Any]:
        """Parse sandbox execution result."""
        if result.stdout:
            try:
                return json.loads(result.stdout.strip())
            except json.JSONDecodeError:
                return {"raw_output": result.stdout.strip()}
        else:
            return {"error": result.stderr or "No output from execution"}

    def analyze_csv_excel(self, file_path: str, query: str) -> Dict[str, Any]:
        """
        Analyze CSV or Excel file using Pandas in E2B sandbox.

        Args:
            file_path: Path to the CSV/Excel file
            query: Natural language query about the data

        Returns:
            Dictionary containing analysis results
        """
        if not self.sandbox:
            return {"error": "Sandbox not initialized"}

        try:
            remote_path = self._upload_file_to_sandbox(file_path)
            code = self._generate_analysis_code(remote_path, query)
            result = self.sandbox.run_code(code)
            return self._parse_execution_result(result)

        except Exception as e:
            return {"error": f"Analysis failed: {str(e)}"}

    def execute_generated_code(self, file_path: str, code: str) -> Dict[str, Any]:
        """
        Execute LLM-generated Python code in the sandbox.

        Args:
            file_path: Path to the CSV/Excel file
            code: Python code generated by LLM

        Returns:
            Dictionary containing execution results
        """
        if not self.sandbox:
            return {"error": "Sandbox not initialized"}

        try:
            self._upload_file_to_sandbox(file_path)
            result = self.sandbox.run_code(code)
            return self._parse_execution_result(result)

        except Exception as e:
            return {"error": f"Code execution failed: {str(e)}"}

    def _get_file_reader(self, file_path: str) -> str:
        """Get appropriate pandas read method for file type."""
        if file_path.endswith('.csv'):
            return f"df = pd.read_csv('{file_path}')"
        elif file_path.endswith(('.xlsx', '.xls')):
            return f"df = pd.read_excel('{file_path}')"
        else:
            raise ValueError("Unsupported file type")

    def _generate_analysis_code(self, file_path: str, query: str) -> str:
        """Generate Python code to analyze the data based on the query."""
        try:
            read_code = self._get_file_reader(file_path)
        except ValueError:
            return "print('Unsupported file type')"

        # Define query patterns more flexibly
        patterns = {
            'regex_enum': ["regex", "enum", "pattern"],
            'required_optional': ["required", "optional", "status"],
            'level_elements': ["level", "elements", "type", "enum"],
            'value_search': ["where", "min length", "max length", "min value", "max value"],
            'blank_analysis': ["blank", "null", "nan", "appears blank"]
        }

        code = f"""
import pandas as pd
import json
import re
import numpy as np

{read_code}

# Clean column names (remove extra spaces)
df.columns = df.columns.str.strip()

# Analyze based on query: {query}
result = {{}}
query = "{query}".lower()

def find_column_by_keywords(df, keywords):
    \"\"\"Find column name that contains any of the keywords\"\"\"
    for col in df.columns:
        if any(keyword.lower() in col.lower() for keyword in keywords):
            return col
    return None

def get_level_columns(df):
    \"\"\"Dynamically find all level columns\"\"\"
    return [col for col in df.columns if 'level' in col.lower()]

def extract_specific_value(df, query):
    \"\"\"Extract specific values based on query patterns\"\"\"
    result_data = {{}}

    # Pattern 1: RegEx/Enum value extraction
    if any(k in query for k in {patterns['regex_enum']}):
        element_match = re.search(r'for\\s+(\\w+)', query)
        if element_match:
            element = element_match.group(1)
            regex_col = find_column_by_keywords(df, ['RegEx', 'Enum', 'Pattern'])
            if regex_col:
                level_cols = get_level_columns(df)
                for level_col in level_cols:
                    if df[level_col].dtype == 'object':
                        matches = df[df[level_col].str.lower() == element.lower()]
                        if not matches.empty:
                            value = matches[regex_col].iloc[0] if not pd.isna(matches[regex_col].iloc[0]) else None
                            if value:
                                result_data.update({{
                                    'regex_enum_value': str(value),
                                    'element': element,
                                    'source_column': regex_col
                                }})
                                break

    # Pattern 2: Required/Optional status
    elif any(k in query for k in {patterns['required_optional']}) and "status" in query:
        req_col = find_column_by_keywords(df, ['Required', 'Optional', 'Mandatory'])
        if req_col:
            field_match = re.search(r'for\\s+(\\w+)', query)
            parent_match = re.search(r'under\\s+(\\w+)', query)

            if field_match:
                field_name = field_match.group(1)
                parent_name = parent_match.group(1) if parent_match else None

                level_cols = get_level_columns(df)
                matches = pd.DataFrame()

                for level_col in level_cols:
                    if df[level_col].dtype == 'object':
                        field_matches = df[df[level_col].str.lower() == field_name.lower()]
                        if not field_matches.empty:
                            if parent_name:
                                # Find parent level dynamically
                                try:
                                    current_level = int(''.join(filter(str.isdigit, level_col)))
                                    parent_level = current_level - 1
                                    parent_col = f"Level {{parent_level}}"
                                    if parent_col in df.columns:
                                        field_matches = field_matches[field_matches[parent_col].str.lower() == parent_name.lower()]
                                except (ValueError, AttributeError):
                                    pass  # Skip if level parsing fails
                            matches = field_matches
                            break

                if not matches.empty:
                    status = matches[req_col].iloc[0] if not pd.isna(matches[req_col].iloc[0]) else None
                    result_data.update({{
                        'required_optional_status': str(status) if status else None,
                        'field': field_name,
                        'parent': parent_name,
                        'source_column': req_col
                    }})

    # Pattern 3: List elements by type
    elif any(k in query for k in {patterns['level_elements']}):
        type_col = find_column_by_keywords(df, ['Type', 'Data Type'])
        if type_col:
            level_match = re.search(r'level\\s+(\\d+)', query)
            type_match = re.search(r'type\\s+(\\w+)', query)

            if level_match and type_match:
                level_num = level_match.group(1)
                type_value = type_match.group(1).upper()

                level_col = f"Level {{level_num}}"
                if level_col in df.columns and df[type_col].dtype == 'object':
                    matches = df[df[type_col].str.upper() == type_value]
                    if not matches.empty:
                        elements = matches[level_col].dropna().unique().tolist()
                        result_data.update({{
                            'level_elements': elements,
                            'level': level_num,
                            'type_filter': type_value,
                            'source_column': level_col
                        }})

    # Pattern 4: Find row by specific value
    elif any(k in query for k in {patterns['value_search']}):
        length_cols = [col for col in df.columns if any(term in col.lower() for term in ['min length', 'max length', 'min value', 'max value'])]

        value_match = re.search(r'is\\s+(\\d+)', query)
        if value_match and length_cols:
            target_value = int(value_match.group(1))

            for col in length_cols:
                try:
                    if df[col].dtype in ['int64', 'float64']:
                        matches = df[df[col] == target_value]
                    else:
                        numeric_values = pd.to_numeric(df[col], errors='coerce')
                        matches = df[numeric_values == target_value]

                    if not matches.empty:
                        result_data.update({{
                            'matching_row': matches.iloc[0].to_dict(),
                            'search_value': target_value,
                            'search_column': col
                        }})
                        break
                except Exception:
                    continue  # Skip problematic columns

    # Pattern 5: Analyze blank/null values
    elif any(k in query for k in {patterns['blank_analysis']}):
        element_match = re.search(r'for\\s+(\\w+)', query)
        if element_match:
            element = element_match.group(1)

            level_cols = get_level_columns(df)
            element_row = None

            for level_col in level_cols:
                if df[level_col].dtype == 'object':
                    matches = df[df[level_col].str.lower() == element.lower()]
                    if not matches.empty:
                        element_row = matches.iloc[0]
                        break

            if element_row is not None:
                blank_cols = []
                max_length_cols = [col for col in df.columns if 'max' in col.lower() and ('length' in col.lower() or 'value' in col.lower())]

                for col in max_length_cols:
                    try:
                        if pd.isna(element_row[col]) or str(element_row[col]).strip() == '':
                            blank_cols.append(col)
                    except KeyError:
                        continue  # Column might not exist

                if blank_cols:
                    result_data.update({{
                        'blank_columns': blank_cols,
                        'element': element,
                        'analysis': "The field appears blank/nan because the CSV structure is inconsistent. The value may have shifted or been missed during parsing.",
                        'full_row': element_row.to_dict()
                    }})
                else:
                    result_data['error'] = f"No blank max length columns found for {{element}}"
            else:
                result_data['error'] = f"Element {{element}} not found"

    return result_data

# Execute the appropriate analysis
if any(keyword in query for keyword in {patterns['regex_enum']}):
    result = extract_specific_value(df, query)
elif any(keyword in query for keyword in {patterns['required_optional']}) and "status" in query:
    result = extract_specific_value(df, query)
elif any(keyword in query for keyword in {patterns['level_elements']}):
    result = extract_specific_value(df, query)
elif any(keyword in query for keyword in {patterns['value_search']}):
    result = extract_specific_value(df, query)
elif any(keyword in query for keyword in {patterns['blank_analysis']}):
    result = extract_specific_value(df, query)
else:
    # Fallback: general data summary
    result['summary'] = {{
        'total_rows': len(df),
        'total_columns': len(df.columns),
        'columns': list(df.columns),
        'data_types': df.dtypes.astype(str).to_dict(),
        'sample_data': df.head(3).to_dict('records')
    }}

print(json.dumps(result, indent=2, default=str))
"""

        return code

# Global instance
data_analyzer = DataAnalyzer()
